### PR TITLE
Remove BEAKER_provision from README

### PR DESCRIPTION
**Pull request by russellshackleford**
BEAKER_provision doesn't seem to have ever worked so remove mention of it to avoid people going down a rabbit hole.

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
I use this all the time so it certainly works. I have to head out now, but just wanted to mention it before I head out. Will respond longer later.

**Comment by russellshackleford** [comment]
> Can you explain the problem you're having,

Basically the same as https://tickets.puppetlabs.com/browse/BKR-494. When talking to @bastelfreak about this in slack, the response was 
> indeed reusing them never worked, as far as I know

Hence the PR to save other people the time trying. However, if it _does_ work I would highly appreciate some documentation to make it work. Even something as simple as a paste in here and I'll test it and change the PR.

**Comment by ekohl** [comment]
So what I always do with beaker_libvirt is:

```console
$ BEAKER_destroy=no bundle exec rake beaker
```

Then I still have a VM running. If a test fails, I run:
```console
$ BEAKER_provision=no BEAKER_destroy=no bundle exec rake beaker
```

That works for me. However, I never got it to work with beaker_docker so perhaps it depends on the provider.

**Comment by ekohl** [comment]
Closing in favor of https://github.com/voxpupuli/voxpupuli-acceptance/pull/76

**Pull request closed without merging**
